CREATE DATABASE IF NOT EXISTS sandrinha;
USE sandrinha;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  senha VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS agendamentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  service VARCHAR(50) NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL
);
